# hydra_ros/docker/dev/docker-compose.yml
# Docker compose for Hydra with development setup for ROS 2
services:
  hydra-dev:
    image: hydra-dev
    build:
      context: ../../../..
      dockerfile: src/hydra_ros/docker/dev/Dockerfile
      network: host
    container_name: hydra-dev
    volumes:
      - ../../../../:/root/hydra_ws
      - ${DATASETS_PATH:-/root/empty_data}:/root/data
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri
    privileged: true
    stdin_open: true
    tty: true